### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by crookesy** [alexmurray/thunderbird-security-classifier#2]
Hey I tried installing by going to extensions then "Install add-on from file" but it didn't recognise any of the files?

Please help

**Comment by alexmurray** [comment]
You can install it by zipping up the contents of the repo as a .zip file and then renaming that as a .xpi - then Thunderbird should recognise it and allow you to install it from a file.

**Comment by crookesy** [comment]
Hey Alex,

Whenever I do it says the file appears to be corrupt, so just to clarify I have to rename it to :thunderbird-security-classifier-master.xpi  ?
Thanks,

**Comment by alexmurray** [comment]
What is the contents of the zip file - it needs to have the repo contents at the top level (root) - so if you have downloaded the repo as a zip file this contains all the contents within a folder name thunderbird-security-classifier - you need to take the contents out of that folder and place it in the root of the zip file.

What Operating System and ZIP program are you using?

**Comment by crookesy** [comment]
Hey Alex,

perhaps you could turn it into an xpi for me?

I'm using windows 10 and 7-zip,

Thanks,

**Comment by alexmurray** [comment]
Sure - see attached (Github doesn't like the .xpi extension so I just renamed it .zip - after downloading rename it to .xpi and it should install).

[thunderbird-security-classifier-master.zip](https://github.com/alexmurray/thunderbird-security-classifier/files/351183/thunderbird-security-classifier-master.zip)
