### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by crookesy** [alexmurray/thunderbird-security-classifier#3]
Hey I have it installed but when I open up an email and write in some stuff. I then proceed to click send and the window doesn't close nor does it send anything?

**Comment by alexmurray** [comment]
Ok - so this has been unmaintained for a while - I haven't used the extension myself for about 4 years so I am not surprised it has broken with upstream changes to Thunderbird - I'll have to look into this and get back to you.

**Comment by crookesy** [comment]
Okay Thankyou, keep me posted ;)

**Comment by alexmurray** [comment]
It sounds similar to the issue people experience with the Click and Send extension - https://addons.mozilla.org/en-US/thunderbird/addon/check-and-send/reviews/ - can you try the suggestion there and see if it helps - ie. open the menu  Thunderbird -> Advanced -> Config editor and then change the option `dom.compartment_per_addon` to `False`

**Comment by crookesy** [comment]
Still not sending...

**Comment by alexmurray** [comment]
Should be fixed now - let me know if that works better for you.

**Comment by crookesy** [comment]
Sorry about this, could you put it back into a .xpi ready .zip file?

**Comment by alexmurray** [comment]
Sure 
[thunderbird-security-classifier-master.zip](https://github.com/alexmurray/thunderbird-security-classifier/files/351399/thunderbird-security-classifier-master.zip)

**Comment by alexmurray** [comment]
Can you confirm if this fixes the issue?

**Comment by crookesy** [comment]
Can confirm this worked. Thanks man.

**Comment by alexmurray** [comment]
FYI - I've added a zip of the final release (identical to the one in the comment above) to the releases page - https://github.com/alexmurray/thunderbird-security-classifier/releases/tag/0.2
